version: '3'
services:
  notebook:
    build:
      context: ./
      dockerfile: Dockerfile
    image: {{ cookiecutter.dockerhub_repo }}:${TAG:-latest}
    volumes:
      - ${HOST_DIR}:/home/jovyan/work
      - ${CERT_DIR}:/etc/ssl/notebook
    user: 'root' # passwordless sudo
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
      GRANT_SUDO: 'yes'
    ports:
      - ${PORT:-0}:8888
    command: "start-notebook.sh \
              --NotebookApp.disable_check_xsrf=True \
              --NotebookApp.password=${PASSWD} \
              ${OPT:---NotebookApp.certfile=/etc/ssl/notebook/mycert.pem --NotebookApp.keyfile=/etc/ssl/notebook/mykey.key}"
