#!/bin/bash

[ -d .dddlab/keys ] || mkdir -p .dddlab/keys


echo "### Generate keys for https encryption"
openssl req -x509 -nodes \
    -days 365 \
    -newkey rsa:2048 \
    -keyout .dddlab/keys/mykey.key \
    -out .dddlab/keys/mycert.pem \
    -subj "/C=US/ST=A/L=B/O=C/OU=D/CN=F" && \
    chmod a+r .dddlab/keys/mykey.key

echo "### download password generating utility"
curl -fSL https://github.com/dddlab/jupyter-passwd/releases/download/v0.1.1/hash-password \
    -o .dddlab/hash-password && \
    chmod u+x .dddlab/hash-password

cat <<EOF > .env
## generated by setup.sh
## variables for docker-compose

HOST_DIR=${PWD}
CERT_DIR=${PWD}/.dddlab/keys
PASSWD=$(.dddlab/hash-password | tail -n1)
EOF
